#!/usr/bin/env bash

alias to="cd"
alias ..="cd .."
alias ...="cd ../.."

alias hide="chflags hidden"
alias unhide="chflags nohidden"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

alias python="python3"
alias activate="source venv/bin/activate"




