#!/usr/bin/env bash

alias to="cd"
alias ..="cd .."
alias ...="cd ../.."
alias h="cd ~"
alias t="cd ~/Desktop"
alias d="cd ~/Developer"
alias dp="cd ~/Developer/projects"
alias dl="cd ~/Developer/learning"

alias hide="chflags hidden"
alias unhide="chflags nohidden"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

alias pip="pip3"
alias python="python3"
alias cv="python3 -m venv venv"
alias av="source venv/bin/activate"
alias dv="deactivate"

# Print each path on a separate line
alias path='echo -e ${PATH//:/\\n}'


