#!/usr/bin/env bash

# runs at login

export EDITOR=vim
export LC_ALL=en_US.utf-8
export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP=~/.pythonstartup.py
export BASH_SILENCE_DEPRECATION_WARNING=1

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"