#!/usr/bin/env bash

# runs at login

export EDITOR=vim
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP=~/.pythonrc.py


export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
