

" DOWNLOAD PLUG.VIM AND PUT IT IN THE `AUTOLOAD` DIRECTORY
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


" INITIALIZE PLUGINS
call plug#begin('~/.vim/plugged')
Plug 'ambv/black'
call plug#end()


" RUN BLACK ON SAVE
autocmd BufWritePre *.py execute ':Black'


" DISABLE ARROW KEYS IN ESCAPE MODE
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>


" DISABLE ARROW KEYS IN INSERT MODE
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>


" ON PRESSING TAB, INSERT 4 SPACES
set tabstop=4
set shiftwidth=4
set expandtab


syntax enable        " ENABLE SYNTAX HIGHLIGHTING
set number           " SHOW LINE NUMBERS
set encoding=utf8    " SET UTF-8 AS STANDARD ENCODING
