#!/usr/bin/env bash

# Folders
alias home="~/"
alias desktop="~/Desktop"
alias developer="${DEVELOPER}" # Write DEVELOPER in .bash_local
alias projects="${DEVELOPER}/projects"
alias learning="${DEVELOPER}/learning"
alias documents="~/Documents"
alias downloads="~/Downloads"

# Go to ...
alias to="cd"
alias ..="cd .."
alias ...="cd ../.."

# Something to hidep
alias hide="chflags hidden"
alias unhide="chflags nohidden"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Python
alias pip="pip3"
alias python="python3"
alias p="python3"
alias pp="ptpython"
alias cv="python3 -m venv venv"
alias av="source venv/bin/activate"
alias dv="deactivate"

# Print each path on a separate line
alias path='echo -e ${PATH//:/\\n}'


