#!/usr/bin/env bash

alias h="~/"
alias t="~/Desktop"
alias d="${DEVELOPER}" # Write DEVELOPER in .bash_local
alias dp="${DEVELOPER}/projects"
alias dl="${DEVELOPER}/learning"
alias D="~/Documents"
alias l="~/Downloads"


alias to="cd"
alias ..="cd .."
alias ...="cd ../.."
alias gh="cd ~"
alias gt="cd ~/Desktop"
alias gD="cd ~/Documents"
alias gl="cd ~/Downloads"
alias gd="cd ${DEVELOPER}"
alias gdp="cd ${DEVELOPER}/projects"
alias gdl="cd ${DEVELOPER}/learning"


alias hide="chflags hidden"
alias unhide="chflags nohidden"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

alias pip="pip3"
alias python="python3"
alias p="python3"
alias pp="ptpython"
alias cv="python3 -m venv venv"
alias av="source venv/bin/activate"
alias dv="deactivate"

# Print each path on a separate line
alias path='echo -e ${PATH//:/\\n}'


