#!/usr/bin/env bash


export EDITOR=vim
export HOSTS="/private/etc/hosts"

export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP=~/.pythonrc.py


# Autocorrect typos in path names when using `cd`
shopt -s cdspell;


[ -f ~/.bash_local ] && source ~/.bash_local
source ~/.aliases
source ~/.bashrc
source ~/.completions
export PATH="/usr/local/opt/ruby/bin:$PATH"

function gi() {
  curl -sL "https://www.gitignore.io/api/$1";
}